version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    working_dir: /code/

    ports:
      - 8000:80
    env_file:
      - .env
    expose:
      - 8000
    volumes:
      - ./src:/code
    tty: true
